#!/bin/bash

# Include some external files
. installer/functions.sh

# Run as root, of course. (this might not be necessary, because we have to run the script somehow with root anyway)

if [[ $(id -u) -ne 0 ]]; then 
  echo "Must be root to run this script."
  exit 87 # Non-root Exit Error
fi

# Non-privileged user settings
. installer/user.sh

. installer/systemd.sh

. installer/ssh.sh

. installer/lamp.sh

. installer/bind.sh

. installer/iptables.sh

. installer/fail2ban.sh

. installer/cron-apt.sh
